---
# tasks file for apm_server

- name: Create APM Server project directory
  ansible.builtin.file:
    path: "{{ elastic_base_dir }}/apm-server"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  become: true

- name: Render apm-server.yml
  ansible.builtin.template:
    src: apm-server.yml.j2
    dest: "{{ elastic_base_dir }}/apm-server/apm-server.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0640"
  become: true
  no_log: "{{ es_security_enabled | bool }}"
  notify: Restart apm-server

- name: Render docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ elastic_base_dir }}/apm-server/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  become: true
  notify: Restart apm-server

- name: Render .env
  ansible.builtin.template:
    src: env.j2
    dest: "{{ elastic_base_dir }}/apm-server/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0640"
  become: true
  notify: Restart apm-server

- name: Bring up APM Server
  community.docker.docker_compose_v2:
    project_src: "{{ elastic_base_dir }}/apm-server"
    state: present
  become: true
