galaxy_info:
  author: Bruno Cochofel
  description: Configure and enable the standalone Elastic Agent pre-installed by Packer
  license: MIT
  min_ansible_version: "2.15"
  galaxy_tags: []
dependencies: []
