galaxy_info:
  author: Bruno Cochofel
  description: Check out and run the upstream OpenTelemetry demo, exporting to APM Server
  license: MIT
  min_ansible_version: "2.15"
  galaxy_tags: []
dependencies: []
