galaxy_info:
  author: Bruno Cochofel
  description: Apply a Data Stream Lifecycle retention policy to logs/metrics/APM data streams
  license: MIT
  min_ansible_version: "2.15"
  galaxy_tags: []
dependencies: []
